### ISSUE TITLE
bug:  Any design that user made in the notes is not showing in that reports.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#47] opened 2023-04-18 09:52 UTC
# Bug Report

Platform: Windows

YATTIE version: 0.5.3.0

**Current behavior:** If the user creates the notes using Unorder list and Order list,
we can not see these changes will not  in the report

**Expected behavior:** The design that the user use in while creating the reports it need to show in the final report 

**Steps to reproduce:**

1. select new test session 
2. choose workspace-->Timeline --->add some Unorder or order list (Use any designs)

**If the user gives the design** 

![image](https://user-images.githubusercontent.com/92415365/232737318-3e9338ee-5af0-4d7d-98e5-b89332a9141c.png)
[](url)
 **The design is missing here**
![image](https://user-images.githubusercontent.com/92415365/232740078-119f33c8-bc8b-442e-97b3-0b2ba28589e5.png)

**Comment by dacoaster** [comment] 2023-04-18 16:16
Thanks for the report @anakhavviswanathan.  This is a duplicate of #41, so I will close it.  It has also been fixed in the upcoming release.

**Comment by dacoaster** [comment] 2023-04-18 16:17
Thanks for the report @anakhavviswanathan. I misunderstood this issue at first glance, so apologies for closing it.  This is very similar to #41 but references a different field.  I will make the fixes in the upcoming release. (v.0.6.0)

**Closed** 2023-05-03 03:30 UTC
Labels: bug

**Comment by dacoaster** [comment] 2023-05-03 03:38
@anakhavviswanathan - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
