### ISSUE TITLE
bug: After minimizes then the test session time will stop and restart again.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#21] opened 2023-03-16 06:23 UTC
# Bug Report

**Platform:** Windows

**YATTIE version:**0.5.3.0

**Current behavior:** **if the user minimizes the yattie then the test session time will stop and restart again.**

**Expected behavior:** The test session should not stop.

**Steps to reproduce:** quick test--> Start session-->click minimize

https://user-images.githubusercontent.com/92415365/225532407-3cc5335e-6732-4aed-87b1-857e5b0c4d6b.mp4

**Comment by dacoaster** [comment] 2023-03-17 19:09
Thank you for this report @anakhavviswanathan.  It looks like the minimize functionality is not working at all on Windows.  I will add this to the list of work being done.

This is how it _should_ work:
![minimize](https://user-images.githubusercontent.com/54721212/225996995-d5cb92b2-ff4e-4d65-94bd-f64806a0a21c.gif)

**Comment by galactidev** [comment] 2023-08-02 03:23
@dacoaster 

This same behavior is also reproducible on macOS Ventura 13.4

**Comment by dacoaster** [comment] 2023-08-28 13:23
Closing this as it is removed in v0.10.0, but fixes will be tracked in #78.

**Closed by dacoaster** 2023-08-28 13:23 UTC
Labels: bug, windows
